### ISSUE TITLE
[1.11.2-1.8.4] can't place log on chopping block

### ISSUE THREAD

**Issue by kreezxil** [gigaherz/Survivalist#34]
When I try to place the log on the chopping block, it appears as a whole block suspended in air above the chopping block.

The server contains the following in it's console:

```
[16:08:21] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Stack can not be invalid!
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: Stack can not be invalid!
        at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:440) ~[OreDictionary.class:?]
        at gigaherz.survivalist.shadow.common.OreDictionaryHelper.hasOreName(OreDictionaryHelper.java:16) ~[OreDictionaryHelper.class:?]
        at gigaherz.survivalist.api.Choppable$ChoppingOreRecipe.accepts(Choppable.java:136) ~[Choppable$ChoppingOreRecipe.class:?]
        at gigaherz.survivalist.api.Choppable.isValidInput(Choppable.java:176) ~[Choppable.class:?]
        at gigaherz.survivalist.chopblock.BlockChopping.func_180639_a(BlockChopping.java:142) ~[BlockChopping.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:446) ~[lz.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:685) ~[mi.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jm.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jm.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

```
but does not crash.

**Comment by gigaherz** [comment]
UGH...! Is it a modded log? I'll check, but I need to know which log it was, and what mods were installed at the same time.

**Comment by kreezxil** [comment]
It's an oak log the standard vanilla one.

-----Original Message-----

**Comment by kreezxil** [comment]
modlist in my pack "colonial expansion"

```
adchimneys
allomancy
appletrees
autosapling
backpacks16840
badwithernocookie
bedbugs
betterwithmods
bloodmagic
cfm
chameleon
cheesemod
chesttransporter
claybucket
coffeespawner
colossalchests
cookingforblockheads
cosmeticarmorreworked
craftingtableiv
creativecore
creativecoredummy
cyclopscore
dailies
easybreeding
eleccore
enderpay
extrarails
farseek
fasterladderclimbing
fastleafdecay
felling
fishing
forge
forgeendertech
forgelin
furniture
furnus
giacomos_bookshelf
giacomosfoundry
gud_coolers
gud_lib
guideapi
hammerz
harvestcraft
holoinventory
hopperducts
jei
largeveins
limelib
literalascension
littletiles
littletilescore
llibrary
mcp
mercurius_updater
minecolonies
minecraft
missing_pieces
morefuelsmod-1.11.x
mxtune
naturescompass
netherportalfix
notenoughwands
plants
platforms
railsplus
redstonepaste
reptilemod
roots
rustic
shadowmc
shetiphiancore
stellarapi
stellarsky
storagedrawers
strait
streams
structuredcrafting
survivalist
terraqueous
tesla
tickprofiler
toolbelt
toroquest
underphangables
underwaterutilities
uniquecrops
usefulnullifiers
vending
villagermarket
waddles
wolfarmor
```

**Comment by LordDan1989** [comment]
Same issue on 1.10.2. I've taken the time to go through Kreezxil's modlist for mods I'm also using and the problem seems to go away upon removing Better with Mods... Which is shite, considering my pack relies heavily on both mods. 👎

**Comment by kreezxil** [comment]
Which is funny as I've asked beetoguy to make a version of his mod that had
just the mill and mill power tech. It's highly possible that he rolled do
many capabilities into betterwithmods that it is now a source of problems.

Good to know about this.

**Comment by LordDan1989** [comment]
@kreezxil See here #47 for solution.
